# Generated by Django 3.0.8 on 2020-07-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200702_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expense',
        ),
    ]
