# Generated by Django 3.0.8 on 2020-07-07 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_purchase_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_category',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='purchase_category',
            unique_together={('category', 'user')},
        ),
    ]
