# Generated by Django 3.0.7 on 2020-07-24 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_user_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
